version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: amazonbot-postgres
    environment:
      POSTGRES_DB: amazonbot
      POSTGRES_USER: amazonuser
      POSTGRES_PASSWORD: amazonpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
